version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: bill-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: bill-redis
    restart: always
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    container_name: bill-localstack
    restart: always
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_AUTH_TOKEN=ignore
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  postgres_data:
  localstack_data: